
  server:
    port: 7001

  data:
    mongodb:
      uri: mongodb://admin:pass@localhost:27017/Xlms?authSource=admin
      database: Xlms

  jpa:
        properties:
          hibernate:
        #dialect: org.hibernate.ogm.datastore.mongodb.MongoDBDialect
            hbm2ddl.auto: update
        #database-platform: org.hibernate.ogm.datastore.mongodb.impl.MongoDBDialect
        show-sql: true
        generate-ddl: true

  #  =======